services:
  fastapi:
    build: app
    ports:
      - '5000:5000'
  
  triton:
    build: triton
    volumes:
      - ./triton/model_repository:/models

      # deploy:
      #   resources:
      #     reservations:
      #       devices:
      #         - driver: nvidia
      #           count: 1
      #           capabilities: [gpu]
