services:
  fastapi:
    build: fastapi
    ports:
      - '5000:5000'
  
  triton:
    build: triton
    volumes:
      - ./triton/model_repository:/models
    ports:
      - '8001:8001'
  
  gradio:
    build: gradio
    ports:
      - '8080:8080'

      # deploy:
      #   resources:
      #     reservations:
      #       devices:
      #         - driver: nvidia
      #           count: 1
      #           capabilities: [gpu]
